<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RollForward>Major</RollForward>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Pandoc.fs" />
    <Compile Include="Browser.fs" />
    <Compile Include="Page.fs" />
    <Compile Include="Scrape.fs" />
    <Compile Include="Wikiru.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" Version="1.59.0" />
  </ItemGroup>
</Project>
