name: push

on:
  workflow_dispatch:
  push:
    branches: master
  pull_request:

permissions:
  contents: read # リポジトリコンテンツの読み取り
  id-token: write # niks3のOIDC認証に必要

jobs:
  nix-flake-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: ncaq/nix-composite-action@6e28cd44693083d063bed5baf36e912c6807a151 # v1.1.1
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check
